events {
    worker_connections 1024;
}

http {
    server {
        listen 80;
        server_name api.contentfor.me obs.contentfor.me nvcf.contentfor.me;

        # Let's Encrypt validation
        location /.well-known/acme-challenge/ {
            root /var/www/certbot;
        }

        # Force SSL
        location / {
            return 301 https://$host$request_uri;
        }
    }

    server {
        listen 443 ssl;
        server_name api.contentfor.me;

        ssl_certificate /etc/letsencrypt/live/api.contentfor.me/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/api.contentfor.me/privkey.pem;

        location / {
            proxy_pass http://kong:8000;
            proxy_set_header Host $host;
        }
    }
    
    server {
        listen 443 ssl;
        server_name obs.contentfor.me;

        ssl_certificate /etc/letsencrypt/live/obs.contentfor.me/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/obs.contentfor.me/privkey.pem;

        location / {
            proxy_pass http://grafana:3000;
            proxy_set_header Host $host;
        }
    }
}
